name: Validate

on: push

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Enable Corepack
              run: corepack enable

            - name: Setup NodeJS and Yarn cache
              uses: actions/setup-node@v4
              with:
                  cache: yarn
                  cache-dependency-path: yarn.lock
                  node-version-file: .nvmrc

            - name: Install dependencies
              run: yarn install

            - name: Transpile
              run: yarn build

            - name: Lint
              run: yarn lint

            - name: Run solutions
              run: yarn test
